sales_site/urls.py
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.flatpages.views import flatpage
from django.urls import path, re_path, include

from blog.views import BlogIndexView
from pages.views import HomePage, OurTeamView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("i18n/", include("django.conf.urls.i18n")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += i18n_patterns(
    path("blog/", BlogIndexView.as_view(), name="blog_index"),
    path("our-team/", OurTeamView.as_view(), name="our-team"),
    path("", HomePage.as_view(), name="home"),
    re_path(r"^(?P<url>.*/)$", flatpage),
    prefix_default_language=False,
)

if settings.DEBUG:
    import debug_toolbar  # noqa

    urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

blog/models.py
from ckeditor.fields import RichTextField
from django.db import models
from django_extensions.db.fields import AutoSlugField


class Category(models.Model):
    name = models.CharField(max_length=150, unique=True, null=False)
    slug = AutoSlugField(populate_from='name')

    class Meta:
        verbose_name = "Category"
        verbose_name_plural = "Categories"

    def __str__(self):
        return self.name

    def __repr__(self):
        return f"<Category id={self.pk} name={self.name}>"


class Post(models.Model):
    title = models.CharField(max_length=150, null=False)
    slug = AutoSlugField(unique=True, populate_from='title')
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True, blank=True)
    content = RichTextField(null=False, blank=False)

    def __str__(self):
        return self.title

    def __repr__(self):
        return f"<Post id={self.pk} title={self.title}>"

pages/models.py
from django.db import models
from django.utils.text import slugify
from imagekit.models import ImageSpecField
from pilkit.processors import SmartResize


def upload_to(instance: "Employee", filename):
    name_slug = slugify(instance.name)
    return "employees/{}/{}".format(name_slug, filename)


class Employee(models.Model):
    name = models.CharField("employee name", max_length=150, null=False, blank=False)
    position = models.CharField("employee position", max_length=150)
    description = models.TextField("extra information")
    photo = models.ImageField(
        "employee photo", upload_to=upload_to, blank=True, null=True
    )

    photo_80x80 = ImageSpecField(
        source="photo",
        processors=[SmartResize(80, 80)],
        format="JPEG",
        options={"quality": 80},
    )
    photo_300x200 = ImageSpecField(
        source="photo",
        processors=[SmartResize(300, 200)],
        format="JPEG",
        options={"quality": 80},
    )

    class Meta:
        ordering = ("id",)

    def __str__(self):
        return self.name

    def __repr__(self):
        return f"<Employee id={self.pk} name={self.name} position={self.position}>"

pages/forms.py
from ckeditor.widgets import CKEditorWidget
from django import forms
from django.contrib.flatpages.forms import FlatpageForm as BaseFlatpageForm


class FlatpageAdminForm(BaseFlatpageForm):
    content = forms.CharField(widget=CKEditorWidget())

blog/views.py
from django.views.generic import ListView

from blog.models import Post


class BlogIndexView(ListView):
    queryset = Post.objects.select_related("category").order_by("-pk").all()
    context_object_name = "posts"

pages/views.py
from django.views.generic import TemplateView, ListView

from blog.models import Post
from .models import Employee


class HomePage(TemplateView):
    template_name = "index.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context["latest_posts"] = Post.objects.all()[:4]

        return context


class OurTeamView(ListView):
    model = Employee

blog/templates/blog/post_list.html
{% extends "base.html" %}

{% block title %}Blog{% endblock %}

{% block content %}
    <h1 class="title is-1 has-text-centered">Blog</h1>
    <hr/>

    <div class="columns is-multiline">
        {% for post in posts %}
            <div class="column is-4">
                <div class="card">
                    <div class="card-content">
                        <div class="media">
                            <div class="media-content">
                                <p class="title is-4">{{ post.title }}</p>
                                <p class="subtitle is-6 has-text-info">{{ post.category.name }}</p>
                            </div>
                        </div>
                        <div class="content">
                            {{ post.content | truncatechars_html:150 | safe }}
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

pages/templates/_partials/footer.html
{% load static %}
<footer class="footer">
    <div class="content has-text-centered">
        <p>
            {% now "jS \o\f F" %}, <strong>Turbo Sales</strong>, <a href="{% static 'secret-config.xml' %}" target="_blank">Secret Config</a>
        </p>
    </div>
</footer>

pages/templates/_partials/header.html
{% load i18n %}
{% load flatpages %}
{% get_flatpages as flatpages %}

<header class="my-4">
    <nav class="navbar" role="navigation">
        <div class="container">
            <div class="navbar-brand">
                <a href="{% url 'home' %}" class="navbar-item">
                    <span class="has-text-weight-bold is-uppercase is-family-monospace is-size-3">Turbo Sales</span>
                </a>
            </div>

            <div class="navbar-menu">
                <div class="navbar-start">
                    <a class="navbar-item"
                       href="{% url "home" %}">{% trans "Home" %}</a>
                    <a class="navbar-item"
                       href="{% url "blog_index" %}">{% trans "Blog" %}</a>
                    <a class="navbar-item"
                       href="{% url "our-team" %}">{% trans "Our Team" %}</a>
                    <div class="navbar-item has-dropdown is-hoverable">
                        <a href="#" class="navbar-link">More pages</a>
                        <div class="navbar-dropdown is-boxed">
                            {% for page in flatpages %}
                                <a class="navbar-item"
                                   href="{{ page.url }}">{{ page.title }}</a>
                            {% endfor %}
                        </div>
                    </div>
                </div>

                <div class="navbar-end">
                    <div class="navbar-item">
                        <div class="buttons">
                            <a href="{% url "admin:index" %}" target="_blank"
                               class="button is-primary">Admin Portal</a>
                        </div>
                    </div>

                    {% load i18n %}

                    <form action="{% url 'set_language' %}"
                          class="mt-3"
                          method="post">{% csrf_token %}
                        <input name="next" type="hidden" value="{{ redirect_to }}">
                        <div class="select">
                            <select name="language">
                                {% get_current_language as LANGUAGE_CODE %}
                                {% get_available_languages as LANGUAGES %}
                                {% get_language_info_list for LANGUAGES as languages %}
                                {% for language in languages %}
                                    <option value="{{ language.code }}"
                                            {% if language.code == LANGUAGE_CODE %}
                                            selected{% endif %}>
                                        {{ language.name_local }} ({{ language.code }})
                                    </option>
                                {% endfor %}
                            </select>
                        </div>
                        <input type="submit" value="Go" class="button is-info">
                    </form>
                </div>
            </div>
        </div>
    </nav>
</header>

pages/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}Sales Site{% endblock %}</title>

    <link rel="stylesheet" href="{% static 'css/bulma.css' %}">
    <link rel="stylesheet" href="{% static 'css/main.css' %}"/>
</head>
<body>
    {% include "_partials/header.html" %}

    {% block hero %}{% endblock %}

    <section class="section">
        <div class="container">
            {% block content %}{% endblock %}
        </div>
    </section>

    {% include "_partials/footer.html" %}
</body>
</html>

pages/templates/index.html
{% extends "base.html" %}

{% block hero %}
    <section class="hero is-medium is-primary">
        <div class="hero-body">
            <div class="container">
                <h1 class="title">
                    Sales for Everyone!
                </h1>
                <h2 class="subtitle">
                    Egestas adipisicing? Beatae iure laudantium pede. Fugiat nobis,
                    mattis curae ex malesuada, soluta quidem, ducimus, optio. Mauris
                    primis esse ante!
                </h2>
            </div>
        </div>
    </section>
{% endblock %}

{% block content %}
    <div class="columns">
        <div class="column is-9 pr-6">
            <div class="columns is-multiline">
                {% for post in latest_posts %}
                    <div class="mb-5 column is-6">
                        {% if post.category_id %}
                            <div class="mb-2">
                                <span class="tag is-primary is-medium">{{ post.category.name }}</span>
                            </div>
                        {% endif %}
                        <p class="title is-4">{{ post.title }}</p>
                        <div class="has-text-justified">
                            {{ post.content | truncatechars_html:250 | safe }}
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
        <div class="column">
            <div class="image">
                <img src="https://images.unsplash.com/photo-1555421689-43cad7100750?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=400&q=80"
                     alt="Picture"/>
            </div>
        </div>
    </div>

    <div class="columns mt-6">
        <div class="column is-3">
            <div class="image">
                <img src="https://images.unsplash.com/photo-1576098788063-9f0dbaa5ccc4?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=400&q=80"
                     alt="Girls"/>
            </div>
        </div>
        <div class="column ml-6">
            <p class="title is-2 has-text-primary">Is it matter?</p>
            <p class="subtitle is-4 has-text-grey is-italic">
                Corrupti excepteur tenetur, aptent, mauris vulputate, dignissimos
                veritatis magni?
            </p>

            <div class="pt-4 has-text-grey-dark has-text-justified">
                <p class="pt-4">Cillum iusto illum, quo neque, distinctio, cupidatat delectus mauris
                    interdum dolore quidem venenatis! Rutrum, incididunt vivamus,
                    conubia varius. A ultricies, ut quidem, est! Elit? Ridiculus
                    quibusdam molestiae mattis orci optio excepturi corrupti venenatis
                    dignissim. Consequuntur, potenti? Provident turpis placerat,
                    iaculis, eleifend aut! Delectus voluptatum omnis, deserunt luctus
                    atque! Maiores ornare.</p>

                <p class="pt-4">Aut turpis fuga fusce imperdiet laboris potenti voluptatum, eum
                    placeat, fusce hic tenetur, laoreet pariatur! Nostra metus sapiente,
                    interdum sapien? Harum, quo potenti maxime potenti hymenaeos?
                    Porttitor posuere! Aliquip fugit dapibus fringilla quod, quos metus
                    consequatur quidem! Maecenas orci felis, maiores in? Venenatis
                    nostra eum molestiae! Minim varius do velit.</p>

                <p class="pt-4">Aenean aute adipiscing, habitasse nibh iste hendrerit consectetur do
                    proident? Suspendisse mattis condimentum quae, augue velit tellus
                    cupiditate! Convallis mauris velit sed modi aperiam, neque
                    excepturi, fermentum sint dui temporibus, facilisis volutpat
                    perferendis, cupiditate rem omnis senectus? Dolorem accusamus cursus
                    eum wisi platea mollit. Mauris necessitatibus? Dui exercitationem,
                    elit amet.</p>
            </div>
        </div>
    </div>
{% endblock %}

pages/templates/pages/_our_team.html
<ul>
    {% for employee in employee_list %}
        <li>
            {% if employee.photo.name %}
                <span><img src="{{ employee.photo_80x80.url }}" alt="{{ employee.name }}"></span>
            {% endif %}
            <strong>{{ employee.name }}</strong> / <em>{{ employee.position }}</em>
        </li>
    {% endfor %}
</ul>

pages/templates/pages/employee_list.html
{% extends "base.html" %}

{% block title %}Our Team{% endblock %}

{% block content %}
    <h1 class="title is-1 has-text-centered">Our Team</h1>
    <hr />

    <div class="columns is-centered is-multiline">
        {% for employee in object_list %}
            <div class="mt-4 column is-3 has-text-centered">
                {% if employee.photo.name %}
                    <div class="my-2">
                        <img src="{{ employee.photo_300x200.url }}"
                             alt="{{ employee.name }}"
                             data-src="{{ employee.photo.url }}"/>
                    </div>
                {% else %}
                    <div style="height: 200px; display: flex; align-items: center; justify-content: center;"
                         class="my-2 has-text-centered has-background-light is-vcentered">
                        <span class="has-text-grey-dark is-capitalized">No Photo</span>
                    </div>
                {% endif %}
                <p class="has-text-primary has-text-weight-bold is-size-4 is-capitalized ">{{ employee.name }}</p>
                <p class="has-text-grey-dark has-text-weight-medium is-size-6 is-italic">{{ employee.position }}</p>
                <p class="has-text-grey-light is-size-6">{{ employee.description }}</p>
            </div>
        {% endfor %}
    </div>
{% endblock %}